---
- name: Converge
  hosts: all
  environment:
    GITHUB_ACTIONS: "maybe"
  vars:
    postgresql:
      databases:
        keycloak:
          name: "keycloak-test"
          owner: ~keycloak
      users:
        keycloak:
          username: "keycloak-test"
          password: "keycloak-test"
    keycloak:
      redirect_admin: yes
      domain: localhost
      config:
        db_username: "keycloak-test"
        db_password: "keycloak-test"
        db_url_database: "keycloak-test"
        hostname_url: "http://localhost:8080"
        hostname_admin_url: "http://localhost:8080/"
        proxy: none
      environment:
        KEYCLOAK_FRONTEND_URL: "http://localhost:8080/auth"
        KEYCLOAK_BASE_URL: "http://localhost:8080"
    system:
      features:
        proserver_user: yes
  tasks:
    - name: "Include ansible-proserver-keycloak"
      ansible.builtin.include_role:
        name: "ansible-proserver-keycloak"
